name: Audit NPM packages

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - develop

jobs:
  install:
    name: 'Install'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main

  yarn-audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node_modules
        uses: OffchainLabs/actions/node-modules/restore@main

      - name: Run audit
        run: yarn audit:ci
